### ISSUE TITLE
Repository setup checklist

### ISSUE THREAD

**Issue by dahiro** [stgallerkb/uxp-poc-demo#1]
> **Heads up!** This issue was created automatically by the automated repository setup workflow. It is intended to use as a reference for fulfilling our standards and ensure that the repository meets them upon creation.

This checklist was generated in [run #5216147747](https://github.com/stgallerkb/.github-private/actions/runs/5216147747) at [.github-private](https://github.com/stgallerkb/.github-private).

## Checklist

Please go through the following points and confirm them accordingly. If you're stuck or are missing information, please check our [official GitHub migration guide](https://sgkb-sow.atlassian.net/l/cp/HdvavKHx) for answers. In case of questions feel free to post them in our GitHub Teams channel and ask Jan Kott or Jan Biasi in case of urgent questions.

### Automated workflow setup

Read [migration guide - configure repository](https://sgkb-sow.atlassian.net/wiki/spaces/SGKBSOW/pages/2182512641/Configure+repository+-+Migration+-+GitHub#Automatic-setup) for more information

- [ ] The [automatic repository setup workflow](https://github.com/stgallerkb/.github-private/actions/runs/5216147747) succeeded
- [ ] The [manual repository setup workflow](https://github.com/stgallerkb/.github-private/actions/workflows/manual-repository-setup.yml) was ran by a developer with the required flags
- [ ] The repository contains a valid dependabot configuration (check `.github/dependabot.yml`) and is adjusted to your project needs
- [ ] The repository contains a valid PR template (check `.github/pull_request_template.yml`) and is adjusted to your project needs
- [ ] The repository contains a valid Codeowners file (check `.github/CODEOWNERS`) and is adjusted to your project needs

### Manual setup

- [ ] The project contains a correct CI (`ci.yml`) workflow, which is created by using our starter workflows and is adjusted to your project needs
- [ ] The project contains a correct CD (`cd.yml`) workflow, which is created by using our starter workflows and is adjusted to your project needs
- [ ] The project contains a correct manual deployment (`manual-deploy.yml`) workflow, which is created by using our starter workflows and is adjusted to your project needs
- [ ] The project contains a correct CodeQL (`codeql.yml`) workflow, which is created by using our starter workflows and is adjusted to your project needs
- [ ] The SonarCloud configuration was migrated from the `bitbucket-pipelines.yml` to a standalone `sonar-project.properties` file
- [ ] The `.release-it.json` configuration was adjusted to include GitHub releases
- [ ] Java projects contain a `.java-version` file in the root directory with the Java version number to be used in it

### Additional steps in case of migration

- [ ] The source code, tags and branches are migrated correctly
- [ ] The Bitbucket repository is set to readonly for everyone, PR merges are prevented correctly
- [ ] The [GitHub migration project](https://github.com/orgs/stgallerkb/projects/3) is updated with the current state

### Configuration

The configuration of this repository should already meet our standards as it automatically applied all necessary settings. However, please ensure that the repository settings meet your additional project needs. Especially verify the following files:

| File                                  | Potential changes and adjustments   |
| ------------------------------------- | ----------------------------------- |
| `.github/dependabot.yml`              | Remove unnecessary package managers |
| `.github/CODEOWNERS`                  | Adjust files and owners             |
| `.github/pull_request_template.md`    | Adjust checklist to project needs   |
| `.github/workflows/codeql.yml`        | Adjust languages to project needs   |
| `.github/workflows/cd.yml`            | Adjust to project environment needs |
| `.github/workflows/manual-deploy.yml` | Adjust to project environment needs |

### Environments

The environments should be created by the manual repository setup workflow in our `.github-private` repository.
Please ensure that all environments are setup correctly, you may want to delete unused environments for certain applications.
